name: GitHub CI Experiments

on:
  push:
    branches: [ "github-macos" ]

env:
  PULL_REQUEST_NUMBER: ${{ github.event.pull_request.number }}
  CHECKOUT_FETCH_DEPTH: 1001

jobs:
  full-matrix-tests:

    strategy:
      matrix:
        os:
          - centos-stream-9
          - debian-stable
          - debian-testing
          - debian-unstable
          - fedora-39
          - fedora-40
          - fedora-rawhide
          - gentoo
          - opensuse-leap
          - opensuse-tumbleweed
          - ubuntu-focal
          - ubuntu-jammy
          - ubuntu-mantic
          - ubuntu-noble
        compiler:
          - { CC: gcc, CXX: g++ }
          - { CC: clang, CXX: clang++ }
        layer:
          - { name: layer-00-default, nick: default }
          - { name: layer-01-minimal, nick: minimal }
          - { name: layer-02-maximus, nick: maximus }
        # exclude:
        #   # Non-clang testing on MacOS is too much work for very little gain
        #   - { os: macos-14, compiler: { CC: gcc, CXX: g++ } }
    runs-on: ubuntu-latest
    container:
      image: squidcache/buildfarm-${{ matrix.os }}:stable
      options: --user 1001 # uid used by worfklow runner

    name:  matrix-tests(${{ matrix.os }},${{ matrix.compiler.CC }},${{ matrix.layer.nick }})
    env:
      CC: ${{ matrix.compiler.CC }}
      CXX: ${{ matrix.compiler.CXX }}


    steps:
      - name: Checkout Sources
        uses: actions/checkout@v4
        with:
          fetch-depth: ${{ env.CHECKOUT_FETCH_DEPTH }}

      - name: Test
        id: test
        run: |
          pwd
          id
          ls -lad .
          touch foo
          ls -la

      # - name: Publish build logs
      #   if: success() || failure()
      #   uses: actions/upload-artifact@v4
      #   with:
      #     name: build-logs-${{ matrix.os }}-${{ matrix.compiler.CC }}-${{ matrix.layer.nick }}
      #     path: btlayer-*.log

  freebsd:
    runs-on: ubuntu-latest
    if: false

    steps:
      - name: Checkout Squid sources
        uses: actions/checkout@v4
        with:
          fetch-depth: ${{ env.CHECKOUT_FETCH_DEPTH }}

      - name: Test
        id: test
        uses: vmactions/freebsd-vm@v1
        with:
          usesh: true
          sync: sshfs
          # release: "14.0" # supported: 12.4, 13.2, 13.3, 14.0
          prepare: |
            pkg install -y \
              autoconf \
              autoconf-archive \
              automake \
              bash \
              cppunit \
              gmake \
              libltdl \
              libtool \
              libxml2 \
              m4 \
              nettle &&
            df .

          run: |
            export MAKE=gmake
            export CFLAGS='-Wno-compound-token-split-by-macro'
            export CC=clang
            export CXX=clang++
            ./test-builds.sh --cleanup

      - name: Publish build logs
        if: success() || failure()
        uses: actions/upload-artifact@v4
        with:
          path: btlayer-*.log

  openbsd:
    runs-on: ubuntu-latest
    if: false

    steps:
      - name: Checkout Squid sources
        uses: actions/checkout@v4
        with:
          fetch-depth: ${{ env.CHECKOUT_FETCH_DEPTH }}

      - name: Test
        id: test
        uses: vmactions/openbsd-vm@v1
        with:
          usesh: true
          sync: sshfs
          # release: "14.0" # supported: 12.4, 13.2, 13.3, 14.0
          prepare: |
            pkg_add \
              autoconf-2.71 \
              automake-1.15.1 \
              bash \
              coreutils \
              cppunit \
              git \
              ggrep \
              gmake \
              libxml \
              libtool \
              m4 \
              metaauto
            mkdir $HOME/bin
            ln -s /usr/local/bin/ggrep $HOME/bin/grep
            ls -ld /usr/local/share/aclocal*

          run: |
            export MAKE=gmake
            export pjobs="-j`gnproc`"
            export AUTOMAKE_VERSION=1.15
            export amver=${AUTOMAKE_VERSION}
            export ACLOCAL_AUTOMAKE_DIR="/usr/local/share/aclocal-${AUTOMAKE_VERSION}"
            export ACLOCAL_PATH="/usr/local/share/aclocal:/usr/local/share/aclocal-${AUTOMAKE_VERSION}"
            export AUTOCONF_VERSION=2.71
            export acver=${AUTOCONF_VERSION}
            export ltver=1.5.26
            export CFLAGS='-Wno-compound-token-split-by-macro'
            export LDFLAGS="-L/usr/local/lib"
            export CC=clang
            export CXX=clang++
            export PATH="$HOME/bin:$PATH"
            ./test-builds.sh --cleanup

      - name: Publish build logs
        if: success() || failure()
        uses: actions/upload-artifact@v4
        with:
          path: btlayer-*.log
