name: GitHub CI Experiments

on:
  push:
    branches: [ "github-macos" ]

env:
  PULL_REQUEST_NUMBER: ${{ github.event.pull_request.number }}
  CHECKOUT_FETCH_DEPTH: 1001

jobs:
  freebsd:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Squid sources
        uses: actions/checkout@v4
        with:
          fetch-depth: ${{ env.CHECKOUT_FETCH_DEPTH }}

      - name: Test
        id: test
        uses: vmactions/freebsd-vm@v1
        with:
          usesh: true
          sync: sshfs
          # release: "14.0" # supported: 12.4, 13.2, 13.3, 14.0
          prepare: |
            pkg install -y \
              autoconf \
              autoconf-archive \
              automake \
              bash \
              cppunit \
              gmake \
              libltdl \
              libtool \
              libxml2 \
              m4 \
              nettle

          run: |
            export MAKE=gmake
            bash ./test-builds.sh --cleanup

      - name: Publish build logs
        if: success() || failure()
        uses: actions/upload-artifact@v4
        with:
          path: btlayer-*.log
