name: Staged commit - OpenBSD

on:
  push:
    branches: [ "openbsd-merge-tests" ]

env:
  # empty except for pull_request events
  PULL_REQUEST_NUMBER: ${{ github.event.pull_request.number }}

jobs:

  openbsd:
    runs-on: ubuntu-22.04

    steps:
      - name: Checkout Sources
        uses: actions/checkout@v4

      - name: Run test-builds
        id: test-builds
        uses: vmactions/openbsd-vm@v1
        with:
          usesh: true
          prepare: |
            pkg_add \
              autoconf-2.72p0 \
              autoconf-archive \
              automake-1.16.5 \
              bash \
              coreutils \
              cppunit \
              git \
              ggrep \
              gmake \
              libltdl \
              libtool \
              libnettle \
              libxml \
              libtool \
              m4 \
              metaauto

            mkdir $HOME/bin
            ln -s /usr/local/bin/ggrep $HOME/bin/grep
            ls -ld /usr/local/share/aclocal*
            ls -l /usr/local/bin/auto*

          run: |
            export MAKE=gmake
            export pjobs="-j`gnproc`"
            export AUTOMAKE_VERSION=1.16
            export amver=${AUTOMAKE_VERSION}
            export ACLOCAL_AUTOMAKE_DIR="/usr/local/share/aclocal-${AUTOMAKE_VERSION}"
            export ACLOCAL_PATH="/usr/local/share/aclocal:/usr/local/share/aclocal-${AUTOMAKE_VERSION}"
            export AUTOCONF_VERSION=2.72
            export acver=${AUTOCONF_VERSION}
            export ltver=2.4.2
            export CFLAGS='-Wno-compound-token-split-by-macro'
            export LDFLAGS="-L/usr/local/lib"
            export PATH="$HOME/bin:$PATH"
            ./test-builds.sh --verbose --aggressively-use-config-cache layer-02-maximus # TODO: test all layers

      - name: Publish build logs
        if: success() || failure()
        uses: actions/upload-artifact@v4
        with:
          name: openbsd-build-logs
          path: btlayer-*.log
